version: "3.8"

services:
  wekan:
    image: wekanteam/wekan:latest
    networks:
      - nginx_web_overlay
    ports:
      - "3001:3001"
    environment:
      - ROOT_URL=http://wekan.local:3001
      - MONGO_URL=mongodb://mongo:27017/wekan

  mongo:
    image: mongo:4.0
    networks:
      - nginx_web_overlay
    volumes:
      - wekan_db:/data/db

networks:
  nginx_web_overlay:
    external: true

volumes:
  wekan_db:
