version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Port HTTP exposé
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Fichier de conf externe
    networks:
      - nginx_web_overlay
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == vm-manager  # NGINX tourne uniquement sur le manager

networks:
  nginx_web_overlay:
    external: true  # Utilisation du réseau déjà créé
