# proxy/nginx/nginx.yml
version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/vm-manager/nginx-cluster-apps/proxy/nginx/nginx.conf
    networks:
      - nginx_web_overlay
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  nginx_web_overlay:
    external: true
