version: "3.8"

services:
  ghost_db:                                           # Base de données pour Ghost
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost_password
    volumes:
      - ghost_db_data:/var/lib/mysql
    networks:
      - ghost_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == vm-sauvegarde

  ghost:                                              # Service Ghost
    image: ghost:5-alpine
    restart: unless-stopped
    environment:
      url: http://ghost.local
      database__client: mysql
      database__connection__host: ghost_db
      database__connection__user: ghost
      database__connection__password: ghost_password
      database__connection__database: ghost
    volumes:
      - ghost_content:/var/lib/ghost/content
    networks:
      - ghost_network
      - nginx_web_overlay
    depends_on:
      - ghost_db
    expose:
      - "2368"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s

volumes:
  ghost_content:
  ghost_db_data:

networks:
  ghost_network:
    external: false
  nginx_web_overlay:
    external: true
