version: "3.8"

services:
  ghost:
    image: ghost:5-alpine
    environment:
      - url=http://ghost.local  # URL publique obligatoire
    volumes:
      - ghost_data:/var/lib/ghost/content  # Volume persistant
    networks:
      - nginx_web_overlay
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == vm-worker2
      restart_policy:
        condition: on-failure

volumes:
  ghost_data:

networks:
  nginx_web_overlay:
    external: true
