version: "3.8"

services:
  ghost:
    image: ghost:5-alpine
    container_name: ghost
    ports:
      - "2368:2368" # Exposé pour debug local, mais non utilisé avec NGINX
    environment:
      - url=http://ghost.local
    volumes:
      - ghost_content:/var/lib/ghost/content
    networks:
      - nginx_web_overlay
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == vm-worker2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      labels:
        - "traefik.enable=false" # Pour éviter conflit si Traefik est utilisé plus tard

volumes:
  ghost_content:

networks:
  nginx_web_overlay:
    external: true
