version: "3.8"

services:
  ghost:
    image: ghost:5-alpine
    restart: unless-stopped

    environment:
      url: http://ghost.local
      database__client: mysql
      database__connection__host: ghost_db
      database__connection__user: ghost
      database__connection__password: ghost_password
      database__connection__database: ghost

    volumes:
      - ghost_content:/var/lib/ghost/content

    networks:
      - ghost_network

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2368"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  ghost_content:

networks:
  ghost_network:
    external: false
