version: "3.8"

services:
  ghost_db:
    image: mariadb:10.6
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost_password

    volumes:
      - ghost_db_data:/var/lib/mysql

    networks:
      - ghost_network

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  ghost_db_data:

networks:
  ghost_network:
    external: false
