version: "3.8"

services:
  ghost_db:                                             # Ghost database service
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost_password
    volumes:
      - ghost_db_data:/var/lib/mysql
    networks:
      - ghost_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == vm-sauvegarde

  ghost:                                                # Ghost service
    image: ghost:5-alpine
    restart: unless-stopped
    environment:
      url: http://ghost.local
      database__client: mysql
      database__connection__host: ghost_db
      database__connection__user: ghost
      database__connection__password: ghost_password
      database__connection__database: ghost
    volumes:
      - ghost_content:/var/lib/ghost/content
    networks:
      ghost_network:                                    # Custom network for Ghost services
      nginx_web_overlay:                                # Connect to the existing nginx overlay network
        aliases:
          - ghost                                       # Alias for nginx to resolve Ghost service
    ports:
      - target: 2368
        published: 2368
        protocol: tcp
        mode: host                                      # Expose Ghost on port 2368 of the host
    depends_on:
      - ghost_db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s

volumes:
  ghost_content:
  ghost_db_data:

networks:
  ghost_network:                                        # Custom network for Ghost services
    external: false

  nginx_web_overlay:                                    # Use the existing nginx overlay network
    external: true