version: "3.8"

services:
  ghost:
    image: ghost:5-alpine
    environment:
      # URL publique pour Ghost
      - url=http://ghost.local
    volumes:
      - ghost_data:/var/lib/ghost/content  # Volume pour le contenu (pages, images, etc.)
    networks:
      - nginx_web_overlay
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == vm-worker2  # Exécution sur vm-worker2
      restart_policy:
        condition: on-failure

volumes:
  ghost_data:

networks:
  nginx_web_overlay:
    external: true
